#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-minitest-reporters
Version  : 1.1.10
Release  : 9
URL      : https://rubygems.org/downloads/minitest-reporters-1.1.10.gem
Source0  : https://rubygems.org/downloads/minitest-reporters-1.1.10.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-ansi
BuildRequires : rubygem-builder
BuildRequires : rubygem-maruku
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-ruby-progressbar

%description
[gem]: https://rubygems.org/gems/minitest-reporters
[travis]: https://travis-ci.org/kern/minitest-reporters

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n minitest-reporters-1.1.10
gem spec %{SOURCE0} -l --ruby > rubygem-minitest-reporters.gemspec

%build
export LANG=C
gem build rubygem-minitest-reporters.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
minitest-reporters-1.1.10.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/minitest-reporters-1.0.17 && rake test --trace && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/minitest-reporters-1.1.10.gem
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/.ruby-gemset
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/README.md
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/assets/default-reporter.png
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/assets/mean_time_reporter.png
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/assets/progress-reporter.png
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/assets/spec-reporter.png
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/lib/minitest/extensible_backtrace_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/lib/minitest/minitest_reporter_plugin.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/lib/minitest/old_activesupport_fix.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/lib/minitest/relative_position.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/lib/minitest/reporters.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/lib/minitest/reporters/ansi.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/lib/minitest/reporters/base_reporter.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/lib/minitest/reporters/default_reporter.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/lib/minitest/reporters/html_reporter.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/lib/minitest/reporters/junit_reporter.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/lib/minitest/reporters/mean_time_reporter.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/lib/minitest/reporters/progress_reporter.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/lib/minitest/reporters/ruby_mate_reporter.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/lib/minitest/reporters/rubymine_reporter.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/lib/minitest/reporters/spec_reporter.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/lib/minitest/reporters/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/lib/minitest/templates/index.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/minitest-reporters.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/test/fixtures/junit_filename_bug_example_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/test/fixtures/mean_time_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/test/fixtures/progress_detailed_skip_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/test/fixtures/progress_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/test/fixtures/sample_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/test/gallery/bad_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/test/gallery/good_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/test/integration/reporters/junit_reporter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/test/integration/reporters/mean_time_reporter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/test/integration/reporters/progress_reporter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/test/unit/minitest/extensible_backtrace_filter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/test/unit/minitest/minitest_reporter_plugin_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/test/unit/minitest/reporters_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/minitest-reporters-1.1.10/test/unit/minitest/spec_reporter_test.rb
/usr/lib64/ruby/gems/2.3.0/specifications/minitest-reporters-1.1.10.gemspec
